import { useState, useEffect } from "react";
import api from "../../services/api";
import ReactMarkdown from "react-markdown";
import styles from "../Dashboard/CreateWorkspaceModal.module.css";

export default function StandupModal({ workspaceId, onClose, isOpen }) {
  const [standup, setStandup] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const fetchStandup = async () => {
    setLoading(true);
    setError("");
    try {
      const res = await api.get(`/workspaces/${workspaceId}/standup`);
      // Strip outer quotes if the AI output has them
      let content = res.data.standup.trim();
      if (content.startsWith('"') && content.endsWith('"')) {
        content = content.substring(1, content.length - 1);
      }
      setStandup(content);
    } catch (err) {
      console.error(err);
      setError("Failed to generate AI standup. Try again.");
    } finally {
      setLoading(false);
    }
  };

  // Only trigger the AI when the user actually opens the modal
  useEffect(() => {
    if (isOpen) {
      fetchStandup();
    }
  }, [isOpen, workspaceId]);

  if (!isOpen) return null;

  return (
    <div className={styles["modal-overlay"]} onClick={onClose}>
      <div
        className={styles["modal-content"]}
        onClick={(e) => e.stopPropagation()}
        style={{ maxWidth: "600px" }}
      >
        <div className={styles["modal-header"]}>
          <h2>AI Daily Standup</h2>
          <p>Generated by AI analyzing recent task activity.</p>
        </div>

        <div
          className={styles["form-group"]}
          style={{
            marginTop: "20px",
            minHeight: "150px",
            background: "var(--bg-secondary)",
            padding: "20px",
            borderRadius: "12px",
            overflowY: "auto",
            maxHeight: "400px",
          }}
        >
          {loading && (
            <p
              style={{
                textAlign: "center",
                color: "var(--text-muted)",
                marginTop: "60px",
                fontWeight: "600",
              }}
            >
              🧠 Connecting and analyzing tasks...
            </p>
          )}
          {error && (
            <p style={{ color: "red", textAlign: "center" }}>{error}</p>
          )}
          {!loading && !error && standup && (
            <div
              className="markdown-content"
              style={{
                color: "var(--text-main)",
                lineHeight: "1.6",
                fontSize: "0.95rem",
              }}
            >
              <ReactMarkdown>{standup}</ReactMarkdown>
            </div>
          )}
        </div>

        <div className={styles["modal-actions"]} style={{ marginTop: "20px" }}>
          <button
            type="button"
            className={styles["cancel-btn"]}
            onClick={onClose}
            disabled={loading}
          >
            Close
          </button>
          <button
            type="button"
            className={styles["submit-btn"]}
            onClick={fetchStandup}
            disabled={loading}
            style={{ background: "var(--accent-ai)", color: "var(--bg-base)" }}
          >
            {loading ? "Generating..." : "Regenerate AI Report"}
          </button>
        </div>
      </div>
    </div>
  );
}
