import { useState, useCallback, useEffect } from "react";
import api from "../../services/api";
import ReactMarkdown from "react-markdown";
import styles from "../Dashboard/CreateWorkspaceModal.module.css";

export default function StandupModal({ workspaceId, onClose, isOpen }) {
  const [standup, setStandup] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const fetchStandup = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const res = await api.get(`/workspaces/${workspaceId}/standup`);
      // Strip outer quotes if the AI output has them
      let content = res.data.standup.trim();
      if (content.startsWith('"') && content.endsWith('"')) {
        content = content.substring(1, content.length - 1);
      }
      setStandup(content);
    } catch (err) {
      console.error(err);
      setError("Failed to generate AI standup. Try again.");
    } finally {
      setLoading(false);
    }
  }, [workspaceId]);

  // Only trigger the AI when the user actually opens the modal
  useEffect(() => {
    if (isOpen) {
      fetchStandup();
    }
  }, [fetchStandup, isOpen]);

  if (!isOpen) return null;

  return (
    <div className={styles["modal-overlay"]} onClick={onClose}>
      <div
        className={styles["modal-content"]}
        onClick={(e) => e.stopPropagation()}
        data-size="wide"
      >
        <div className={styles["modal-header"]}>
          <h2>AI Daily Standup</h2>
          <p>Generated by AI analyzing recent task activity.</p>
        </div>

        <div
          className={styles["form-group"]}
          data-standup-panel
        >
          {loading && (
            <p className={styles["standup-loading"]}>
              Connecting and analyzing tasks...
            </p>
          )}
          {error && (
            <p className={styles["standup-error"]}>{error}</p>
          )}
          {!loading && !error && standup && (
            <div className={styles["markdown-content"]}>
              <ReactMarkdown>{standup}</ReactMarkdown>
            </div>
          )}
        </div>

        <div className={styles["modal-actions"]}>
          <button
            type="button"
            className={styles["cancel-btn"]}
            onClick={onClose}
            disabled={loading}
          >
            Close
          </button>
          <button
            type="button"
            className={styles["submit-btn"]}
            onClick={fetchStandup}
            disabled={loading}
            data-variant="ai"
          >
            {loading ? "Generating..." : "Regenerate AI Report"}
          </button>
        </div>
      </div>
    </div>
  );
}
