import { useState, useEffect } from "react";
import api from "../../services/api";
import styles from "../Dashboard/CreateWorkspaceModal.module.css"; 

export default function StandupModal({ workspaceId, onClose, isOpen }) {
  const [standup, setStandup] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const fetchStandup = async () => {
    setLoading(true);
    setError("");
    try {
      const res = await api.get(`/workspaces/${workspaceId}/standup`);
      setStandup(res.data.standup);
    } catch (err) {
      setError("Failed to generate AI standup. Try again.");
    } finally {
      setLoading(false);
    }
  };

  // Only trigger the AI when the user actually opens the modal
  useEffect(() => {
    if (isOpen) {
      fetchStandup();
    }
  }, [isOpen, workspaceId]);

  if (!isOpen) return null;

  return (
    <div className={styles["modal-overlay"]} onClick={onClose}>
      <div className={styles["modal-content"]} onClick={(e) => e.stopPropagation()} style={{ maxWidth: "600px" }}>
        
        <div className={styles["modal-header"]}>
          <h2>🤖 AI Daily Standup</h2>
          <p>Generated by Llama 3 analyzing recent task activity.</p>
        </div>

        <div className={styles["form-group"]} style={{ marginTop: "20px", minHeight: "150px", background: "var(--bg-secondary)", padding: "15px", borderRadius: "12px", overflowY: "auto", maxHeight: "400px" }}>
          
          {loading && <p style={{ textAlign: "center", color: "var(--text-muted)", marginTop: "60px", fontWeight: "600" }}>🧠 Connecting to Groq and analyzing tasks...</p>}
          {error && <p style={{ color: "red", textAlign: "center" }}>{error}</p>}
          {!loading && !error && standup && (
            <pre style={{ whiteSpace: "pre-wrap", fontFamily: "inherit", fontSize: "0.95rem", color: "var(--text-main)", lineHeight: "1.6" }}>
              {standup}
            </pre>
          )}

        </div>

        <div className={styles["modal-actions"]} style={{ marginTop: "20px" }}>
          <button type="button" className={styles["cancel-btn"]} onClick={onClose} disabled={loading}>Close</button>
          <button type="button" className={styles["submit-btn"]} onClick={fetchStandup} disabled={loading} style={{ background: "var(--accent)" }}>
            {loading ? "Generating..." : "Regenerate AI Report"}
          </button>
        </div>

      </div>
    </div>
  );
}
